-- Insertar datos de ejemplo en la tabla 'recipes'
INSERT INTO recipes (title, time, servings, tag, dish_type, collection, category, ingredients, instructions, image, note) VALUES
('Estofado de Vegetales', '45 mins', '4 personas', 'vegano', 'Estofado', 'Colección de Invierno', 'Plato Principal', 'zanahorias, papas, cebollas, tomates', 'Picar todas las verduras y cocinar a fuego lento en una olla grande durante 45 minutos.', 'https://example.com/image1.jpg', 'Perfecto para el clima frío'),
('Lasaña de Carne Clásica', '90 mins', '6 personas', 'tradicional', 'Pasta', 'Colección Familiar', 'Plato Principal', 'carne molida, pasta para lasaña, queso, salsa de tomate', 'Montar la lasaña intercalando capas de pasta, carne, salsa y queso, y hornear durante 45 minutos.', 'https://example.com/image2.jpg', 'Una receta siempre popular en reuniones familiares'),
('Pollo al Curry', '60 mins', '4 personas', 'picante', 'Curry', 'Sabores Asiáticos', 'Plato Principal', 'pollo, curry en polvo, leche de coco, cebollas', 'Cocinar el pollo con cebollas, agregar curry en polvo y leche de coco, cocinar hasta que esté tierno.', 'https://example.com/image3.jpg', 'Ideal para los amantes de los sabores intensos'),
('Paella Valenciana', '120 mins', '8 personas', 'mariscos', 'Arroz', 'Colección Española', 'Plato Principal', 'arroz, camarones, mejillones, pollo, guisantes, pimientos', 'Cocinar todos los ingredientes en una paella grande, añadir azafrán para el color.', 'https://example.com/image4.jpg', 'Un clásico del verano español'),
('Ensalada Caprese', '10 mins', '2 personas', 'fresco', 'Ensalada', 'Colección de Verano', 'Entrada', 'tomates, mozzarella, albahaca, aceite de oliva', 'Alternar capas de tomate y mozzarella, adornar con albahaca y rociar con aceite de oliva.', 'https://example.com/image5.jpg', 'Ligera y refrescante para días calurosos'),
('Tacos de Carnitas', '180 mins', '6 personas', 'tradicional', 'Tacos', 'Sabores Mexicanos', 'Plato Principal', 'carne de cerdo, cebolla, cilantro, limón, tortillas de maíz', 'Cocinar la carne de cerdo lentamente hasta que esté deshebrable, servir en tortillas con cebolla y cilantro.', 'https://example.com/image6.jpg', 'Un favorito para cualquier reunión'),
('Gazpacho Andaluz', '20 mins', '4 personas', 'vegano', 'Sopa', 'Colección Española', 'Entrada', 'tomate, pimiento, pepino, ajo, vinagre', 'Mezclar todos los ingredientes y servir frío.', 'https://example.com/image7.jpg', 'Refrescante y nutritivo para el verano'),
('Risotto de Champiñones', '50 mins', '4 personas', 'vegetariano', 'Arroz', 'Colección Italiana', 'Plato Principal', 'arroz arborio, champiñones, caldo de verduras, parmesano', 'Cocinar el arroz lentamente añadiendo caldo poco a poco y agregar los champiñones salteados al final.', 'https://example.com/image8.jpg', 'Cremoso y lleno de sabor'),
('Empanadas de Carne', '120 mins', '12 empanadas', 'tradicional', 'Empanadas', 'Sabores Latinos', 'Aperitivo', 'masa para empanadas, carne molida, cebolla, huevo duro', 'Rellenar las obleas de empanada con la carne cocida, cebolla y huevo, luego hornear.', 'https://example.com/image9.jpg', 'Perfectas para picar');
